apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: pelorus.charts.pelorus.konveyor.io
spec:
  group: charts.pelorus.konveyor.io
  names:
    kind: Pelorus
    listKind: PelorusList
    plural: pelorus
    singular: pelorus
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Configure a running instance of Pelorus
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: 'PelorusSpec defines state of the Pelorus application and
              allows to configure for the desired workflow. More information about
              Pelorus configuration that can be used in the Spec section is available
              at: https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/PelorusCore/'
            properties:
              exporters:
                description: |-
                  References configuration for the Pelorus exporters. More info about exporters configuration: https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/PelorusExporters/


                    Example:
                      instances:
                        - app_name: < instance_name >
                          enabled: < won't be created if set to false >
                          exporter_type: < deploytime, committime, failure >
                type: object
                x-kubernetes-preserve-unknown-fields: true
              prometheus_retention:
                description: 'Prometheus Retention time. More information: https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/PelorusCore/#prometheus_retention'
                type: string
              prometheus_retention_size:
                description: 'Prometheus Retention Size. More information: https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/PelorusCore/#prometheus_retention_size'
                type: string
              prometheus_storage:
                description: 'Use Prometheus Persistent Volume. More information:
                  https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/PelorusCore/#prometheus-persistent-volume'
                type: boolean
              prometheus_storage_pvc_capacity:
                description: Prometheus Persistent Volume capacity.
                type: string
              prometheus_storage_pvc_storageclass:
                description: Prometheus Persistent Volume storage class to be used.
                type: string
            type: object
          status:
            description: Status defines the observed state of Pelorus
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
