site_name: Pelorus Documentation
theme: readthedocs
nav:
  - Introduction:
    - Welcome to Pelorus: index.md
    - Our Philosphy: Philosophy.md
  - Using Pelorus:
    - Architecture: Architecture.md
    - Installation: Install.md
    - Demo: Demo.md
    - Configuration: Configuration.md
    - MinIO for Long Term Storage: MinIO.md
  - Dashboards:
    - Dashboard Summary: Dashboards.md
    - Software Delivery Performance: dashboards/SoftwareDeliveryPerformance.md
  - Pelorus Development:
    - Dev Guide: Development.md
