site_name: Pelorus Docs
site_url: https://pelorus.readthedocs.io/en/latest/
site_description: Metrics that matter
repo_name: konveyor/pelorus
repo_url: https://github.com/konveyor/pelorus
theme:
  name: material
  logo: img/icon-white.png
  favicon: img/favicon.png
  font:
    text: Red Hat Text
    code: Red Hat Monospace
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: pelorus
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.instant
  custom_dir: overrides
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting_started/Install.md
    - Quickstart Tutorial: getting_started/Demo.md
    - Configuration: getting_started/configuration2.md
    - Troubleshooting: getting_started/Troubleshooting.md
    - Uninstall: getting_started/Uninstall.md
    - Dashboards: Dashboards.md
  - Our Philosophy:
    - Overview: philosophy/index.md
    - The Problem Today: philosophy/problem.md
    - Finding the Right Bridge Outcomes: philosophy/bridge_outcomes.md
    - Outcomes:
      - Overview: philosophy/outcomes/index.md
      - Software Delivery Performance: philosophy/outcomes/SoftwareDeliveryPerformance.md
      - Platform Adoption: philosophy/outcomes/platform_adoption.md
    - philosophy/pelorus.md
  - Configuration:
    - Architecture: Architecture.md
    - Configuration: Configuration.md
    - NooBaa for Long Term Storage: Noobaa.md
  - Contribution:
    - Dev Guide: Development.md
    - Upstream Support: UpstreamSupport.md
plugins:
  - social
watch:
- overrides
