app_name: deploytime-exporter
#env_from_secrets: 
#- github-secret
#extraEnv:
#- name: APP_LABEL
#  value: foo
source_context_dir: exporters/committime
source_ref: master
source_url: https://github.com/redhat-cop/pelorus.git
scrapeInterval: 5m