# For details refer to the documentation:
#       https://pelorus.readthedocs.io/en/latest/Configuration/#commit-time-exporter

apiVersion: v1
kind: ConfigMap
metadata:
  name: committime-config
  namespace: pelorus
data:
  API_USER: "default"            # ""  |  User's github username, can be overriden by env_from_secrets
  TOKEN: "default"           # ""  |  User's Github API Token, can be overriden by env_from_secrets
  GIT_API: "default"         # api.github.com  |  Github Enterprise API FQDN, can be overriden by env_from_secrets
  GIT_PROVIDER: "default"    # github  |  github, gitlab, or bitbucket
  TLS_VERIFY: "default"      # True
  NAMESPACES:                #     | Restricts the set of namespaces,  comma separated value "myapp-ns-dev,otherapp-ci"
  COMMIT_HASH_ANNOTATION: "default"     # io.openshift.build.commit.id | commit hash annotation name associated with the Build
  COMMIT_REPO_URL_ANNOTATION: "default" # io.openshift.build.source-location | commit repository URL annotation name associated with the Build
