{{- define "prometheus_scrape_config"}}
  {{- with .Values.federate_openshift_monitoring }}
  {{- if .enabled }}
- job_name: 'federate'
  scrape_interval: 15s
  honor_labels: true
  metrics_path: '/federate'
  params:
    'match[]':
    {{- if .metrics_filter }}
      {{ .metrics_filter | toYaml }}
    {{- else }}
      - '{job="kube-state-metrics"}'
      - '{job="openshift-state-metrics"}'
    {{- end }}
  static_configs:
    - targets:
      # This is a statically named endpoint that should be the same in all clusters
      - 'prometheus-k8s.openshift-monitoring.svc:9091'
  scheme: https
  tls_config:
    #insecure_skip_verify: true
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
  authorization:
    credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  {{- end }}
  {{- end }}
  {{- range .Values.federated_prometheus_hosts }}
  - job_name: "federated-prometheus-{{ .id }}"
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="openshift-state-metrics"}'
    scheme: "https"
    basic_auth:
      username: 'internal'
      password: "{{ .password }}"
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - "{{ .hostname }}"
        labels:
          federated_job: "federated-prometheus-{{ .id }}"
  {{- end }}
  {{- range .Values.external_prometheus_hosts }}
  - job_name: "external-prometheus-{{ .id }}"
    scrape_interval: 15s
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - "{{ .hostname }}"
        labels:
          external_job: "external-prometheus-{{ .id }}"
  {{- end }}
{{- end }}
{{- if or .Values.federated_prometheus_hosts .Values.external_prometheus_hosts .Values.federate_openshift_monitoring.enabled }}
---
apiVersion: v1
data:
  prometheus-additional.yml: {{ include "prometheus_scrape_config" . | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: pelorus-prometheus-additional-scrape-configs
{{- end}}
