apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pelorus
spec:
  groups:
  - name: software-delivery-performance
    rules: 
    - record: sdp:lead_time:by_commit
      expr: >
        min by (app, commit) (deploy_timestamp - on(app,image_sha) group_left(commit) commit_timestamp)
    - record: sdp:lead_time:by_app
      expr: >
        avg by (app) (sdp:lead_time:by_commit)
    - record: sdp:lead_time:global
      expr: >
        avg(sdp:lead_time:by_app)
    - record: sdp:time_to_restore:by_issue
      expr: >
        failure_resolution_timestamp - failure_creation_timestamp
    - record: sdp:time_to_restore:by_app
      expr: >
        avg by (app) (sdp:time_to_restore:by_issue)
    - record: sdp:time_to_restore:global
      expr: >
        avg (sdp:time_to_restore:by_app)
    - record: fr:change_failure_rate
      expr: >
        count(failure_creation_timestamp) / count(deploy_timestamp)
