apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-pelorus
  labels:
    prometheus: prometheus-pelorus
spec:
  {{- if eq (.Values.prometheus_storage | toString) "true" }}
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.prometheus_storage_pvc_storageclass }}
        storageClassName: {{ .Values.prometheus_storage_pvc_storageclass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.prometheus_storage_pvc_capacity | default "2Gi" }}
  {{- end }}
  {{- if .Values.bucket_access_point }}
  thanos:
    image: quay.io/thanos/thanos:{{ .Values.thanos_version | default "v0.28.0" }}
    version: {{ .Values.thanos_version | default "v0.28.0" }}
    objectStorageConfig:
      key: thanos.yaml
      name: thanos-objstore-config
  {{- end }}
  replicas: 2
  replicaExternalLabelName: ""
  ruleNamespaceSelector: {}
  ruleSelector: {}
  serviceAccountName: pelorus-prometheus
  serviceMonitorSelector: {}
{{- if .Values.extra_prometheus_hosts}}
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yml
{{- end }}
{{- if .Values.custom_ca }}
  configMaps:
    - cluster-ca-bundle
{{- end }}
  secrets:
    - prometheus-pelorus-tls
    - prometheus-pelorus-htpasswd
  containers:
  - args:
    - -provider=openshift
    - -https-address=:9091
    - -http-address=
    - -email-domain=*
    - -upstream=http://localhost:9090
    - -htpasswd-file=/etc/proxy/htpasswd/auth
    - -openshift-service-account=pelorus-prometheus
    - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
    - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}'
    - -tls-cert=/etc/tls/private/tls.crt
    - -tls-key=/etc/tls/private/tls.key
    - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
    - -cookie-secret=bacon
    - -openshift-ca=/etc/pki/tls/cert.pem
    - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
{{- if .Values.custom_ca }}
    - -openshift-ca=/etc/prometheus/configmaps/cluster-ca-bundle/ca-bundle.crt
{{- end}}
    - -skip-auth-regex=^/metrics
    image: image-registry.openshift-image-registry.svc.cluster.local:5000/openshift/oauth-proxy:v4.4
    name: prometheus-proxy
    ports:
    - containerPort: 9091
      name: web-tls
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 100Mi
    volumeMounts:
    - mountPath: /etc/tls/private
      name: secret-prometheus-pelorus-tls
    - mountPath: /etc/proxy/htpasswd
      name: secret-prometheus-pelorus-htpasswd
{{- if .Values.custom_ca }}
    - name: configmap-cluster-ca-bundle
      readOnly: true
      mountPath: /etc/prometheus/configmaps/cluster-ca-bundle
{{- end }}

