apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pelorus
spec:
  groups:
  - name: software-delivery-performance
    rules: 
    - record: sdp:lead_time:by_app
      expr: >
        deploy_timestamp - on(image_sha) group_left commit_timestamp
    - record: sdp:lead_time:global
      expr: >
        avg(sdp:lead_time:by_app)
    - record: fr:time_to_restore
      expr: >
        failure_resolution_timestamp - failure_creation_timestamp
    - record: fr:time_to_restore:global
      expr: >
        avg(fr:time_to_restore)
    - record: fr:change_failure_rate
      expr: >
        count(fr:time_to_restore) / count(deploy_timestamp)